# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

name: "Dependabot"


on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/scanning" # Location of package manifests
    schedule:
      interval: "weekly"
